#!/bin/sh

# Checks for release commits with commit message e.g. v1.1.
# If it’s a release commit, checks for proper versions and date
# set in meson.build, in NEWS and in AppData.

RELEASE="$(grep -E '^v[0-9]+(\.[0-9]+){1,2}$' "$1")"
test "$RELEASE" = "" && exit 0

maint/check-news $RELEASE