#!/bin/bash

# Take a valid configuration as input
INPUT="config-test.asr"

# Remove old files
rm invalid*.asr

# Generate invalid configurations with only one detail changed
sed '1s;^;NoGroup = 1\n\n;'     $INPUT > invalid-key-without-group.asr
sed 's/^\[Model\]/[ledoM]/g'    $INPUT > invalid-missing-group-model.asr
sed '/^Name =/d'                $INPUT > invalid-missing-key-name.asr
sed '/^Plugin =/d'              $INPUT > invalid-missing-key-plugin.asr
sed '/^BaseFolder =/d'          $INPUT > invalid-missing-key-basefolder.asr
sed 's/^Name =.*$/Name =/g'     $INPUT > invalid-empty-key-name.asr
sed 's/^Plugin =.*$/Plugin =/g' $INPUT > invalid-empty-key-plugin.asr
sed 's/^Language =.*$/Language =/g' \
                                $INPUT > invalid-empty-key-language.asr