#!/bin/bash

# Changes to meson build dir
# Must be run from a subfolder of project's root folder

if [ "$1" != "" ] ; then
	if [ -d ../"$1"/meson-private ] ; then
		cd ../"$1" || exit 1
		return
	else
		echo "$1 is not a meson build dir."
		exit 1
	fi
fi

FIND_CMD="find ../ -maxdepth 2 -name meson-private"
BUILDS=$($FIND_CMD | wc -l)

if [ "$BUILDS" -eq 0 ] ; then
	echo "Please build the project first."
	exit 1
elif [ "$BUILDS" -gt 1 ] ; then
	echo "Scripts operates on one build only. Found more:"
	$FIND_CMD
	echo "You can add the build dir as an argument to the script."
	exit 1
fi

cd "$($FIND_CMD -exec dirname '{}' \;)" || exit 1
