#!/bin/bash

cd "$(dirname "$0")" || exit 1

source command_exists_or_exit "codespell"

cd ..

codespell --skip="./build,./debian,./.git,*.po,*.pot,*.ogg,*.png,*.ico,*.xcf" \
	  --ignore-words-list="dur" \
	  --quiet-level=4