#!/bin/bash
# Creates HTML help and copies it to GitHub pages.
# Relies on my personal directory setup.
# First (optional) argument is the meson build dir, if there are several build dirs

WEBDIR=../parlatype-website/help-online


cd "$(dirname "$0")" || exit 1

cd ..
rm -r ${WEBDIR:?}/*
yelp-build html -o $WEBDIR/ help/C/
