#!/bin/bash
# Creates reference and launches a webbrowser to show it.
# First (optional) argument is the meson build dir, if there are several build dirs

BROWSER=firefox

cd "$(dirname "$0")" || exit 1
source cd_builddir_or_exit

if meson configure | grep -s -e 'gtk-doc.*false' ; then
	meson configure -Dgtk-doc=true
fi

if ninja parlatype-doc; then
	$BROWSER libparlatype/docs/reference/html/index.html &
fi