#!/bin/bash
# Creates reference and launches a webbrowser to show it.

BROWSER=firefox

cd "$(dirname "$0")" || exit 1
source cd_builddir_or_exit

if meson configure | grep -s -e 'gtk-doc false' ; then
	meson configure -Dgtk-doc=true
fi

ninja parlatype-doc
$BROWSER libparlatype/docs/reference/html/index.html &