#!/bin/bash
# Runs the whole test suite under Valgrind.
# First (optional) argument is the meson build dir, if there are several build dirs
# Returns 0 if no memory leaks found.

TESTS="config gst player waveloader waveviewer"
LOG='meson-logs/testlog-valgrind.txt'
SUPPS='../maint/valgrind-suppression'
VALGRIND="valgrind --tool=memcheck \
                   --leak-check=full \
                   --leak-resolution=high \
                   --num-callers=20 \
                   --suppressions=$SUPPS/glib.supp \
                   --suppressions=$SUPPS/gst.supp \
                   --suppressions=$SUPPS/gtk.supp \
                   --suppressions=$SUPPS/pt.supp"


cd "$(dirname "$0")" || exit 1
source cd_builddir_or_exit

meson test --wrap="$VALGRIND" \
           --timeout-multiplier=10 \
             $TESTS  # command fails, if $TESTS is quoted

# Show report
grep -E -e '^# Start|ERROR SUMMARY' $LOG | sed 's/# //g' | sed 's/==.*SUMMARY: //g'

ERRORS=$(grep -e 'ERROR SUMMARY' $LOG | grep -v -c -e 'SUMMARY: 0 errors')
exit "$ERRORS"